spring.application.name=DeployDock
deploydock.security.issuer=deploydock
deploydock.security.access-token-ttl=PT1H
deploydock.security.jwt-secret=${DEPLOYDOCK_JWT_SECRET}
deploydock.kubernetes.control-namespace=${DEPLOYDOCK_CONTROL_NAMESPACE:deploydock-system}
deploydock.kubernetes.namespace-access-group=
deploydock.kubernetes.namespace-access-resource=pods
deploydock.kubernetes.namespace-access-verb=list
