apiVersion: v1
kind: Namespace
metadata:
  name: deploydock-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploydock
  namespace: deploydock-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploydock-account-store
  namespace: deploydock-system
rules:
  - apiGroups: ["deploydock.io"]
    resources: ["deploydockusers"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["deploydock.io"]
    resources: ["deploydockpermissionpolicies"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploydock-account-store
  namespace: deploydock-system
subjects:
  - kind: ServiceAccount
    name: deploydock
    namespace: deploydock-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploydock-account-store
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploydock-namespace-access-reviewer
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles"]
    verbs: ["escalate", "bind"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploydock-namespace-access-reviewer
subjects:
  - kind: ServiceAccount
    name: deploydock
    namespace: deploydock-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploydock-namespace-access-reviewer
